apiVersion: v1
kind: Service
metadata:
  name: hola-nbc-chart
  namespace: training
  labels:
    app: hola-nbc-chart
spec:
  ports:
  - port: 8000
    targetPort: 8000
  selector:
    app: hola-nbc-chart
  type: {{ .Values.service.type }}
