# Default values for open5gs-epc-helm.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

open5gs:
  image:
    repository: mdalgitsis/open5gs
    tag: "2.4.11"
    pullPolicy: IfNotPresent

webui:
  image:
    repository: mdalgitsis/open5gs-webui
    tag: "latest"
    pullPolicy: IfNotPresent

# mongo configuration on NFs (BSF, PCF, UDR, WEBUI)
db_uri: mongodb://mongodb-svc:27017/open5gs

# mondodb
mongodb:  
  image:
    repository: mongo
    tag: "latest"  
    pullPolicy: Always

# Data Network Names
dnn: internet

amf:
  mcc: '001'
  mnc: '01'
  tac: '1'

# Primary/Native kubernetes interface
k8s:
 interface: eth0