FROM node:19-alpine3.16

RUN apk update && apk add git && \
    git clone https://github.com/open5gs/open5gs.git

WORKDIR /open5gs/webui

RUN npm install && \
    npm run build

CMD npm run start

EXPOSE 3000