apiVersion: v1
kind: Service
metadata:
  name: amf-sbi-svc
  labels:
    nf-type: amf
spec:
  selector:
    nf-type: amf
  ports:
    - name: sbi
      protocol: TCP
      port: 7777   
      targetPort: sbi
  type: ClusterIP     

---
apiVersion: v1
kind: Service
metadata:
  labels:
    nf-type: amf
  name: amf-ngap-svc
spec:
  type: NodePort
  selector:
    nf-type: amf
  ports:
    - name: ngap 
      protocol: SCTP
      port: 38412  # Service port
      targetPort: ngap # Pod port
      #nodePort: "" 

---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: amf-depl
  labels:
    nf-type: amf
spec:
  replicas: 1
  selector:
    matchLabels:
      nf-type: amf
  template:
    metadata:
      labels:
        nf-type: amf
    spec:    
      containers:
        - name: amf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["/bin/sh"]
          args: ["-c", "/open5gs/install/bin/open5gs-amfd -c /open5gs/config-map/amf.yaml"]
          ports:
            - name: sbi
              containerPort: 7777
            - name: ngap
              containerPort: 38412
              protocol: SCTP
          volumeMounts:
          - name: amf-cmap
            mountPath: /open5gs/config-map/amf.yaml
            subPath: "amf.yaml"
      volumes:
        - name: amf-cmap
          configMap:
            name: amf-cmap