apiVersion: v1
kind: ConfigMap
metadata:
  name: ausf-cmap
  labels:
    nf-type: ausf
data:
  ausf.yaml: |
    logger:
        file: /open5gs/ausf.log

    ausf:
      sbi:
      - dev: {{ .Values.k8s.interface }}
        port: 7777
        advertise: ausf-svc

    nrf:
     sbi:
     - name: nrf-svc
       port: 7777