apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: open5gs-mongodb
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: open5gs-mongodb
spec:
  serviceName: "mongodb-svc"
  selector:
    matchLabels:
      app: open5gs-mongodb
  template:
    metadata:
      labels:
        app: open5gs-mongodb
    spec:
      containers:
      - image: "{{ .Values.mongodb.image.repository }}:{{ .Values.mongodb.image.tag }}"
        name: open5gs-mongodb
        imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
        command:
          - mongod
        args:
          - "--bind_ip=0.0.0.0"
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-persistent-storage
        emptyDir: {}

