apiVersion: v1
kind: ConfigMap
metadata:
  name: pcf-cmap
  labels:
    nf-type: pcf
data:
  pcf.yaml: |
    logger:
        file: /open5gs/pcf.log
    
    db_uri: "{{ .Values.db_uri }}"    

    pcf:
      sbi:     
      - dev: {{ .Values.k8s.interface }}
        port: 7777
        advertise: pcf-svc
    
    nrf:
     sbi:
     - name: nrf-svc
       port: 7777 