apiVersion: v1
kind: ConfigMap
metadata:
  name: udr-cmap
  labels:
    nf-type: udr
data:
  udr.yaml: |
    logger:
        file: /open5gs/udr.log

    db_uri: "{{ .Values.db_uri }}"

    udr:
      sbi:
      - dev: "{{ .Values.db_uri }}"   
        port: 7777
        advertise: udr-svc

    nrf:
     sbi:
     - name: nrf-svc
       port: 7777  