FROM python:3.6-alpine

RUN mkdir -p /usr/src/app
RUN mkdir -p /root/.kube

WORKDIR /usr/src/app

COPY requirements.txt /usr/src/app/

RUN pip3 install --no-cache-dir -r requirements.txt

COPY . /usr/src/app

EXPOSE 8000

ENTRYPOINT ["python3"]

CMD ["-u", "index.py"]