apiVersion: v1
kind: ConfigMap
metadata:
  name: bsf-cmap
  labels:
    nf-type: bsf
data:
  bsf.yaml: |
    db_uri: "{{ .Values.db_uri }}"

    logger:
        file: /open5gs/bsf.log

    bsf:
      sbi:
      - dev: {{ .Values.k8s.interface }}
        port:
        advertise: bsf-svc

    nrf:
     sbi:
    - name: nrf-svc
      port: 7777