apiVersion: v1
kind: Service
metadata:
  name: mongodb-svc
spec:
  ports:
  - port: 27017
    targetPort: 27017
  selector:
    app: open5gs-mongodb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: open5gs-mongodb
spec:
  selector:
    matchLabels:
      app: open5gs-mongodb
  template:
    metadata:
      labels:
        app: open5gs-mongodb
    spec:
      containers:
      - image: free5gmano/nextepc-mongodb
        name: open5gs-mongodb
        ports:
        - containerPort: 27017
          name: mongodb
        volumeMounts:
        - name: mongodb-persistent-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-persistent-storage
        persistentVolumeClaim:
          claimName: mongodb-pv-claim

---
{{- if .Values.mongodb.persistent_volume.enabled }}

kind: PersistentVolume
apiVersion: v1
metadata:
  name: mongodb-pv-volume
  labels:
    type: local
spec:
  storageClassName: ""
  capacity:
    storage: {{ .Values.mongodb.storage_capacity }}
  accessModes:
    - ReadWriteOnce
  claimRef:
     namespace: {{ .Release.Namespace }}
     name: mongodb-pv-claim
  hostPath:
    path: "/mnt/"

{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongodb-pv-claim
spec:
  accessModes:
    - ReadWriteOnce
{{ if .Values.mongodb.persistent_volume_claim.storage_class.enabled }}
  storageClassName: {{ .Values.mongodb.persistent_volume_claim.storage_class.name }}
{{ else }}
  storageClassName: ""
{{ end }}
  resources:
    requests:
      storage: {{ .Values.mongodb.storage_capacity }}