apiVersion: v1
kind: ConfigMap
metadata:
  name: nssf-cmap
  labels:
    nf-type: nssf
data:
  nssf.yaml: |
    logger:
        file: /open5gs/nssf.log

    nssf:
      sbi:     
      - dev: {{ .Values.k8s.interface }}
        port: 7777
        advertise: nssf-svc
      
      nsi:
      - addr: nrf-svc
        port: 7777
        s_nssai:
          sst: 1        
    nrf:
     sbi:
      name: nrf-svc