apiVersion: v1
kind: Service
metadata:
  name: pcf-svc
  labels:
    nf-type: pcf
spec:
  selector:
    nf-type: pcf
  ports:
    - name: sbi
      protocol: TCP
      port: 7777 
      targetPort: sbi  
---  
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: pcf-depl
  labels:
    nf-type: pcf
spec:
  replicas: 1
  selector:
    matchLabels:
      nf-type: pcf
  template:
    metadata:
      labels:
        nf-type: pcf
    spec:    
      containers:
        - name: pcf
          image: "{{ .Values.open5gs.image.repository }}:{{ .Values.open5gs.image.tag }}"
          imagePullPolicy: {{ .Values.open5gs.image.pullPolicy }}
          command: ["/bin/sh", "-c"]
          args:
          - cd /open5gs;
            ./install/bin/open5gs-pcfd -c /open5gs/config-map/pcf.yaml;
            echo '********* Should not get here --> this means PCF is broken!'
          ports: 
            - name: sbi
              containerPort: 7777
          volumeMounts:
          - name: pcf-cmap
            mountPath: /open5gs/config-map/pcf.yaml
            subPath: "pcf.yaml"          
      volumes:
        - name: pcf-cmap
          configMap:
            name: pcf-cmap  