apiVersion: v1
kind: ConfigMap
metadata:
  name: smf-cmap
  labels:
    nf-type: smf
data:
  smf.yaml: |
    logger:
        file: /open5gs/smf.log

    parameter:
        no_ipv6: true

    smf:
        sbi:     
        - dev: "{{ .Values.db_uri }}" 
          port: 7777
          advertise: smf-sbi-svc
        pfcp:
           dev: {{ .Values.k8s.interface }}
           port: 8805
        gtpc:
          dev: {{ .Values.k8s.interface }}
        gtpu:
          dev: {{ .Values.k8s.interface }}    
        subnet:
         - addr: 10.45.0.1/16
           dnn: {{ .Values.dnn }}
        dns:
          - 8.8.8.8
          - 8.8.4.4
        mtu: 1400

    nrf:
     sbi:
     - name: nrf-svc
       port: 7777

    upf:
      pfcp:
        - name: upf-pfcp-svc
          port: 8805
          dnn: {{ .Values.dnn }}