apiVersion: v1
kind: Service
metadata:
  name: open5gs-webui
  labels:
    nf-type: webui
spec:
  type: NodePort
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30080 # Node port
  selector:
    nf-type: webui

---
apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: open5gs-webui 
  labels:
    nf-type: webui
spec:
  replicas: 1
  selector:
    matchLabels:
      nf-type: webui
  template:
    metadata:
      labels:
        nf-type: webui
    spec:    
      containers:
      - name: webui
        imagePullPolicy: {{ .Values.webui.image.pullPolicy }}
        image: "{{ .Values.webui.image.repository }}:{{ .Values.webui.image.tag }}"      
        env:
        - name: DB_URI
          value: "{{ .Values.db_uri }}"
        - name: NODE_ENV
          value: "production"  
        - name: HOSTNAME
          value: '0.0.0.0'  